services:
  psi-risk-dt:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: psi-risk-dt
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace
    command: tail -f /dev/null